name: client
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  image_picker: ^0.8.7+5
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.1.0
  provider: ^6.0.1
  flutter_dotenv: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/.env
  uses-material-design: true
